### ISSUE TITLE
Movies are scanned and sorted too

### ISSUE THREAD

**Issue by torrottum** [torrottum/TVSort#3]
* `The.Hobbit.The.Desolation.Of.Smaug.2013.1080p.BluRay.DTS.x264-HDMaNiAcS.mkv` are moved into `The Hobbit the Desolation of Smaug/Season 20`
* `Die Hard 1988 1080p BluRay Remux AVC DTS-HD MA 5.1 - KRaLiMaRKo.mkv` are moved into `Die Hard/Season 19`

**Comment by torrottum** [comment]
The object from `epinfer.parse()` contains a `_score` property.
After some testing it seems that if the score is above 300 the file will most likely be a TV show.
There will be some false negatives, like for example `BBC.Horizon.2014.Whats.Wrong.with.Our.Weather.720p.HDTV.x264.AAC.MVGroup.org.mkv`, but that's because it's a unconventional TV show filename (no season or episode)

## Test results
Filename     | Score | TV Show
------------ | ----- | ------- |
BBC.Horizon.2014.Whats.Wrong.with.Our.Weather.720p.HDTV.x264.AAC.MVGroup.org.mkv | 257.6 | yes
Bones.S10E01.The.Conspiracy.In.The.Corpse.720p.WEB-DL.DD5.1.H.264-ECI.mkv | 360.6 | yes
Bones.S10E08.720p.HDTV.x264-KILLERS.mkv | 395 | yes
Die Hard 1988 1080p BluRay Remux AVC DTS-HD MA 5.1 - KRaLiMaRKo.mkv | 129 | no
Elementary.S03E01.1080p.WEB-DL.DD5.1.H.264-Juggalotus.mkv | 344.9 | yes
Elmentary.S03E08.720p.HDTV.X264-DIMENSION.mkv | 395 | yes
Irreversible.2002.720p.BluRay.x264-PHOBOS.mkv | 157 | no
Shameless.US.S05E01.720p.HDTV.x264-KILLERS.mkv | 395 | yes
Solan Og Ludvig - Jul i Flaaklypa 2013 1080p Remux AVC FLAC 5.1-NorTV.mkv | 146.9 | no
South.Park.S18E01.Go.Fund.Yourself.1080p.WEB DL.AAC2.0.H.264-NTb.mkv | 353 | yes
South.Park.S18E10.720p.HDTV.x264-KILLERS.mkv | 395 | yes
The.Book.of.Life.2014.1080p.BluRay.DD.5.1.x264-HDMaNiAcS.mkv | 171.9 | yes
The.Culture.High.2014.1080p.WEBRiP.x264-RAiNDEER.mkv | 211.8 | yes
The.Hobbit.The.Desolation.Of.Smaug.2013.1080p.BluRay.DTS.x264-HDMaNiAcS.mkv | 186.9 | no
The.Simpsons.S26E08.Covercraft.1080p.WEB-DL.DD5.1.H.264-NTb.mkv | 356.9 | yes

**Comment by skerit** [comment]
I've actually been thinking about adding movie rules to `epinfer` for a while now.
All the current rules are currently in epinfer's `init.js` file: https://github.com/skerit/epinfer/blob/master/lib/init.js

It wouldn't be too hard to create a new 'movie' subtype, unfortunately right now all the format, codecs, ... stuff is part of the 'episode' subtype so I've got to do a few rewrites first.

**Comment by torrottum** [comment]
Awesome. There's a lot of changes planned for TVSort. I just haven't gotten the time to work on it.
